# Generated by Django 5.1.6 on 2025-02-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polytechnicien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='picture',
        ),
    ]
